/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chneau.openhours;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class OpenHoursTest {
    @Test
    public void testSomeLibraryMethod() {
        OpenHours classUnderTest = OpenHours.Parse("");
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
